### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by killercup** [mbrlabs/distance#1]
FYI, [strsim](https://github.com/dguo/strsim-rs) is a similar project with a few more algorithms (I'm _not_ the author). 'distance' is a far better name. I've struggled to remember 'strsim' every time I wanted to use it!

**Comment by mbrlabs** [comment]
Oh..and i thought i finally found a useful first crate to publish /:
Thanks for the info though ;)

**Comment by killercup** [comment]
There's room for more than one crate that does this :) Even if you just re-export the other algorithms form strsim with a unified API, it would help as your crate is far easier to find.

**Comment by mbrlabs** [comment]
Yeah, you're right. 
But i think i'm going to reinvent the wheel and implement the algorithms on my own. New ones will follow soon ;)

**Comment by killercup** [comment]
Still awesome. Implementing cool algorithms in Rust never hurt anybody (hopefully)!
